### ISSUE TITLE
[BUG] : Moving the install folder to an invalid folder loses data

### ISSUE THREAD

**Issue by blimmo** [Zagrios/bs-manager#206]
When moving the install folder to a path that is invalid the transfer fails with an error message and all data is lost.

**To Reproduce**
1. Open the settings to installation folder.
2. Choose a folder that already contains a folder called "BSManager"

**Expected behavior**
Error message and nothing happens.

**Actual behavior**
Error message and all installs, maps, etc. are deleted.

**Desktop:**
 - OS: Windows 10

**Comment by Zagrios** [comment]
I'm sorry you had this problem, I tried to reproduce it but it worked fine for me...
Could you give me the logs at the date you had the problem? 
Be careful, the logs may contain your name and surname because of the file paths (you can send them to us on discord if you want)

**Comment by blimmo** [comment]
Sorry I may have been a little unclear about exactly what was wrong with the folder I chose.
I created a folder "BeatSaber/BSManager" and chose this as the folder initially. Since BSManager creates its own folder inside wherever you choose I then had "BeatSaber/BSManager/BSManager" so I chose "BeatSaber" directly instead. This obviously still contained the "BeatSaber/BSManager" folder I originally created which conflicted with the folder BSManager was trying to create.

Here is the relevant section of the logs:
```[2023-04-08 19:11:31.500] [info]  try get version from folder C:\Users\Peter\Documents\BSManager\BSInstances\1.28.0
[2023-04-08 19:11:31.506] [info]  try get version from folder C:\Users\Peter\Documents\BSManager\BSInstances\Beat Saber 1.27.0
[2023-04-08 19:11:31.510] [info]  try get version from folder C:\Users\Peter\Documents\BSManager\BSInstances\depot_620981
[2023-04-08 19:14:55.362] [error] Error: ENOENT: no such file or directory, rename 'C:\Games\BeatSaber\BSManager\BSManager' -> 'C:\Games\BeatSaber\BSManager'
[2023-04-08 19:15:18.847] [info]  Checking for update
[2023-04-08 19:15:20.153] [info]  Update for version 1.1.0 is not available (latest version: 1.1.0, downgrade is disallowed).
[2023-04-08 19:16:55.427] [info]  try get version from folder C:\Games\BeatSaber\BSManager\BSInstances\depot_620981
[2023-04-08 19:17:29.376] [error] TypeError: Cannot read properties of undefined (reading 'steam')
    at v.getVersionPath (C:\Users\Peter\AppData\Local\Programs\bs-manager\resources\app\dist\main\main.js:8:919101)
    at d.isFolderLinked (C:\Users\Peter\AppData\Local\Programs\bs-manager\resources\app\dist\main\main.js:8:953359)
    at C:\Users\Peter\AppData\Local\Programs\bs-manager\resources\app\dist\main\main.js:8:889384
    at IpcMainImpl.<anonymous> (C:\Users\Peter\AppData\Local\Programs\bs-manager\resources\app\dist\main\main.js:8:930493)
    at IpcMainImpl.emit (node:events:527:28)
    at EventEmitter.<anonymous> (node:electron/js2c/browser_init:161:11120)
    at EventEmitter.emit (node:events:527:28)
[2023-04-08 19:17:32.395] [error] Unhandled Exception UnhandledRejection Error: ENOENT: no such file or directory, scandir 'C:\Games\SteamLibrary\steamapps\common\Beat Saber\Beat Saber_Data\CustomLevels'
[2023-04-08 19:17:59.219] [error] Unhandled Exception UnhandledRejection Error: ENOENT: no such file or directory, scandir 'C:\Games\SteamLibrary\steamapps\common\Beat Saber\Beat Saber_Data\CustomLevels'
[2023-04-08 19:17:59.236] [error] Unhandled Exception UnhandledRejection Error: ENOENT: no such file or directory, scandir 'C:\Games\SteamLibrary\steamapps\common\Beat Saber\Beat Saber_Data\CustomLevels'
[2023-04-08 19:18:03.093] [info]  try get version from folder C:\Games\BeatSaber\BSManager\BSInstances\depot_620981
```

I believe the error at 19:14:55 is the only relevant line. The detailed error at 19:17:29 occurs throughout the logs and the errors at 19:17:32 are likely caused by no longer having a valid CustomLevels since the steam install was linked to the shared maps.

**Comment by Zagrios** [comment]
Thank you, I succeed to reproduce the exact same error, I will fix it quickly 👌

**Comment by Zagrios** [comment]
Fixed here #210
