### ISSUE TITLE
[BUG] : Playlist OneClick Installation fails with 'Invalid URL'

### ISSUE THREAD

**Issue by belzebub40k** [Zagrios/bs-manager#342]
## Bug Description
When trying to install playlists from https://scoresaber.balibalo.xyz/peepee the OneClick installation fails with error 'Invalid URL'

## Reproduction Steps
Enable OneClick installation for playlists and for example try to install this playlist.
```
bsplaylist://playlist/https%3A%2F%2Fscoresaber.balibalo.xyz%2Fcustom-playlist%2Fto-improve-2023-10-29.bplist%3Ft%3DTo%2520improve%2520(2023-10-29)%26i%3D349732.373247.488472.293053.437539.419438.407397.288955.345843.295904.434899.537237.182483.286891.313893.348169.489022.322986.382759.325001.346264.495120.400744.378819.292946.437193.203739.540728.526368.335373.28187.1904.321594.372342.295516.360552.417148.373473.348660.322458.535719.86814.418647.370713.418012.339196.467531.535804.11176.347671
```

## Expected Behavior
Installation of the playlist should work without throwing and error. I tried the same URL with ModAssistant without receiving an error.

## Logs
```
[2023-10-29 21:50:42.635] [info]  DISPATCH bsplaylist://playlist/https%3A%2F%2Fscoresaber.balibalo.xyz%2Fcustom-playlist%2Fto-improve-2023-10-29.bplist%3Ft%3DTo%2520improve%2520(2023-10-29)%26i%3D349732.373247.488472.293053.437539.419438.407397.288955.345843.295904.434899.537237.182483.286891.313893.348169.489022.322986.382759.325001.346264.495120.400744.378819.292946.437193.203739.540728.526368.335373.28187.1904.321594.372342.295516.360552.417148.373473.348660.322458.535719.86814.418647.370713.418012.339196.467531.535804.11176.347671
[2023-10-29 21:50:42.635] [info]  DEEP-LINK RECEIVED FROM bsplaylist bsplaylist://playlist/https%3A%2F%2Fscoresaber.balibalo.xyz%2Fcustom-playlist%2Fto-improve-2023-10-29.bplist%3Ft%3DTo%2520improve%2520(2023-10-29)%26i%3D349732.373247.488472.293053.437539.419438.407397.288955.345843.295904.434899.537237.182483.286891.313893.348169.489022.322986.382759.325001.346264.495120.400744.378819.292946.437193.203739.540728.526368.335373.28187.1904.321594.372342.295516.360552.417148.373473.348660.322458.535719.86814.418647.370713.418012.339196.467531.535804.11176.347671
[2023-10-29 21:50:43.531] [error] TypeError: Invalid URL
    at new NodeError (node:internal/errors:399:5)
    at new URL (node:internal/url:560:13)
    at request (node:https:346:32)
    at get (node:https:394:15)
    at e._subscribe (C:\Users\belzebub\AppData\Local\Programs\bs-manager\resources\app.asar\dist\main\main.js:14:972885)
    at e._trySubscribe (C:\Users\belzebub\AppData\Local\Programs\bs-manager\resources\app.asar\dist\main\main.js:14:635476)
    at C:\Users\belzebub\AppData\Local\Programs\bs-manager\resources\app.asar\dist\main\main.js:14:635398
    at Object.t.errorContext (C:\Users\belzebub\AppData\Local\Programs\bs-manager\resources\app.asar\dist\main\main.js:14:749888)
    at e.subscribe (C:\Users\belzebub\AppData\Local\Programs\bs-manager\resources\app.asar\dist\main\main.js:14:635301)
    at C:\Users\belzebub\AppData\Local\Programs\bs-manager\resources\app.asar\dist\main\main.js:14:713067
[2023-10-29 21:50:43.531] [error] TypeError: Invalid URL
    at new NodeError (node:internal/errors:399:5)
    at new URL (node:internal/url:560:13)
    at request (node:https:346:32)
    at get (node:https:394:15)
    at e._subscribe (C:\Users\belzebub\AppData\Local\Programs\bs-manager\resources\app.asar\dist\main\main.js:14:972885)
    at e._trySubscribe (C:\Users\belzebub\AppData\Local\Programs\bs-manager\resources\app.asar\dist\main\main.js:14:635476)
    at C:\Users\belzebub\AppData\Local\Programs\bs-manager\resources\app.asar\dist\main\main.js:14:635398
    at Object.t.errorContext (C:\Users\belzebub\AppData\Local\Programs\bs-manager\resources\app.asar\dist\main\main.js:14:749888)
    at e.subscribe (C:\Users\belzebub\AppData\Local\Programs\bs-manager\resources\app.asar\dist\main\main.js:14:635301)
    at C:\Users\belzebub\AppData\Local\Programs\bs-manager\resources\app.asar\dist\main\main.js:14:713067
[2023-10-29 21:50:43.548] [error] [
  "Uncaught TypeError: Cannot read properties of undefined (reading 'progression')",
  'file:///C:/Users/belzebub/AppData/Local/Programs/bs-manager/resources/app.asar/dist/renderer/renderer.js',
  2,
  565048,
  "Error: Cannot read properties of undefined (reading 'progression')"
]
```

## System Specs
-   OS: Windows 11 Pro
-   Version: 22H2

**Comment by Zagrios** [comment]
Thanks for all the details! I will fix that for the next release 👌
