### ISSUE TITLE
[BUG] :  token problems

### ISSUE THREAD

**Issue by MichelTheBard** [Zagrios/bs-manager#423]
## Bug Description
after placing in my oculus token, it just shows that my login token may be invalid, even though I followed everything perfectly. 
## Expected Behavior
I expected to login and download the latest version

## Screenshots
![image_2024-02-14_122501549](https://github.com/Zagrios/bs-manager/assets/160019513/0fdceaeb-ffb0-43c6-ac09-ca63d8d01671)

## Additional context
none

**Comment by SpaceDose** [comment]
I got the same problem with the following error in the logfile. (BSManager v1.4.5 on Windows 11)

```
[2024-02-14 18:38:45.879] [info]  Checking if Oculus user token is valid
[2024-02-14 18:38:45.879] [info]  Oculus user token is valid. token lenght : 175
[2024-02-14 18:38:46.083] [error] Error: End of data reached (data length = 0, asked index = 4). Corrupted zip ?
    at i.checkIndex (C:\Users\user\AppData\Local\Programs\bs-manager\resources\app.asar\dist\main\main.js:14:338390)
    at i.checkOffset (C:\Users\user\AppData\Local\Programs\bs-manager\resources\app.asar\dist\main\main.js:14:338303)
    at i.readData (C:\Users\user\AppData\Local\Programs\bs-manager\resources\app.asar\dist\main\main.js:14:339942)
    at i.readString (C:\Users\user\AppData\Local\Programs\bs-manager\resources\app.asar\dist\main\main.js:14:338809)
    at l.isSignature (C:\Users\user\AppData\Local\Programs\bs-manager\resources\app.asar\dist\main\main.js:14:354807)
    at l.readEndOfCentral (C:\Users\user\AppData\Local\Programs\bs-manager\resources\app.asar\dist\main\main.js:14:357052)
    at load (C:\Users\user\AppData\Local\Programs\bs-manager\resources\app.asar\dist\main\main.js:14:358799)
    at C:\Users\user\AppData\Local\Programs\bs-manager\resources\app.asar\dist\main\main.js:14:331725
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at t.OculusDownloader.getManifest (C:\Users\user\AppData\Local\Programs\bs-manager\resources\app.asar\dist\main\main.js:14:984347) DOWNLOAD_MANIFEST_FAILED
```

**Comment by Zagrios** [comment]
Hi make sure you own Beat Saber on the Oculus Rift (PC) store, owning it on the store for the headset doesn't meen you own the PC version.
Also make sure you've followed this guide (Token from Meta website doesn't work anymore) : https://github.com/Zagrios/bs-manager/wiki/How-to-obtain-your-Oculus-Token

**Comment by Zagrios** [comment]
Don't hesitate to re-open if needed
