### ISSUE TITLE
[BUG] : Stuck in download or update mods

### ISSUE THREAD

**Issue by Nekoraru22** [Zagrios/bs-manager#565]
## Bug Description
When I try to download or update mods of any version it gets stuck in random percentages for no reason, I close the program, try again and it gets stuck in a different percentage. A couple of friends have tried to do the same and everything works correctly, I have also tried to reinstall it several times deleting all system folders that had to do with the program and the problem persists.

## Reproduction Steps

1. Add a new version (in this case 1.29.0)
2. Go to mods
3. Select new mods
4. Try to install

## Screenshots

https://github.com/user-attachments/assets/c8804392-a525-4695-b674-551198c9520a

After that video the game would not open and I had to reinstall the version. If I try enough times (a lot) I get it to finish the download process and things work correctly, but it's very complicated...

## System Specs

- Windows 11 23H2 (all updated)
- AMD Ryzen 5 3600
- RTX 2060
- 16Gb RAM

**Comment by silentrald** [comment]
Hi @Nekoraru22, are you using the 1.4.8 version of BSManager? Also can you send the snippet of the error logs from BSManager, just follow the steps here [this is on the discord group chat]
![image](https://github.com/user-attachments/assets/a633e32c-67a9-4d68-b953-f485fa1b5c1b)

**Comment by Nekoraru22** [comment]
Hi @silentrald,

Yes, im using the 1.4.8 version. The error logs:

[2024-8-22-v1.4.8.log](https://github.com/user-attachments/files/16849559/2024-8-22-v1.4.8.log)

**Comment by silentrald** [comment]
@Nekoraru22 

Hmmm, weirdly enough the logs said that you've downloaded all your mods just fine by just comparing the timestamp of the video and the logs you've sent. It just didn't update the progress bar for some reason. Can you delete the latest log and then re-replicate the issue but wait for like 3-5 minutes before closing the program and sending the logs just to verify that you're just experiencing a UI issue?

---

Also, it seems that BSManager throttled the beatsaver website by redownloading the mods multiple times. Seems like an unhandled bug in BSManager. If you see this in the logs, like a status 429, just wait for a little bit, a minute or just to be sure 5 minutes, before you can redownload the mods again.

```
[2024-08-22 21:49:57.991] [error] Error: HTTP error! status: 429 https://beatsaver.com/api/maps/hash/115d10630ca566010e6548ed0a6df0ca3267a3f9,75eac6d275552670911b0428ff11bb38a9ffbf3c,69e494f4a295197bf03720029086fabe6856fbce,cc0a109eec7b99327a9221e7189642c7d2021ac1,479037e38d3d631ea51139462a5333d76e4b810f,8a8641ba63b6288555ed8a4574e2bfb95155711b,d4cedb0fc434789f3a88994cbf20d8389f891fcc,9c3fb705f347a46b8bde8d4221e4447ebdb858b5,83036b233f5429a85aedb0cf1ae9c554498b50b6,9c7201c25290e8de798770eab374f0249b1bcee5,16a457c5ceeb408adeeacea53ce31d2ea493647e,53e9542794da8e12a01b2b5fd3737674f1b7fbec,5a6ecfec1a678ed2df7e366744e16e77c061b82a,3c37d1264fc2754051b4045ac84909cdf0703d62,6254580c9ab17f367298e7a7b78986fb58d2a1c8,d01bea2d41e431af205393795a71740b7c188d4d,2385c7df0a693b378066db19b1da64902024f535,67935d25caf0996a282e87ac7a21738812b629dd,559113d5c4247438c6ecad852c61d03d79396af1,ecff1d6f09f180581bdb187fc3e6c7b639f04e5d,8369b04572c428bcbbe511e8db6c68a69b02ee41,f2444f0bffb7d2bab08eb5c457f7a0f53e1e2985,ff2126d0a76f6e57b5b881d200194fc1ff30b3c2,35d58f383a4b13c385c37b4ed6ff6460b765c29a,7e42ec811c5948b413c728b52129d31b69b906e7,696113c37609449e94d6b0f33a7e2ac28faf73c7,3569841e50ebfb50246aaddfd0752ca6ec5c9c3d,a51425319d892986a4867388153bce45b3c28483,ae17294e266bf34f7b3d2a3f40329347f072aacc,cab8cc7fdcce43489dc65e275b8fcae7444715b1,b24adfd730d5f8607890743d5b7a18da36577427,71ff5e91972c87304873a02276ce6a9d80691ee9,33f7950e5d92996727d514c78d5d30242d371761,bcea96043773b95362844ec20ba5149f51b38f70,8ca2ea0911d102f1cc637eaa0a6bc0114327b604,b713ae90a9ce8834b6b8bbce65f27ddf7bbc51ab,9102a2152ed870745006858ea037818f6a1eae81,b68bf61ac6be0e128be32a85810d42e7c53f4756,0f3cd1e0cfc05fdb2fd59852a5f456e32f88ba9e
    at p.getJSON (C:\Users\Neko\AppData\Local\Programs\bs-manager\resources\app.asar\dist\main\main.js:14:1058353)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at i.getMapsDetailsByHashs (C:\Users\Neko\AppData\Local\Programs\bs-manager\resources\app.asar\dist\main\main.js:14:1064848)
    at C:\Users\Neko\AppData\Local\Programs\bs-manager\resources\app.asar\dist\main\main.js:14:1066126
    at async Promise.allSettled (index 27)
    at s.getMapDetailsFromHashs (C:\Users\Neko\AppData\Local\Programs\bs-manager\resources\app.asar\dist\main\main.js:14:1066076)
```

**Comment by silentrald** [comment]
I think I see the problem, seems that the BSIPA install is timing out which is a bug on version `1.4.8`.

You can download the pre-release version `1.5.0-alpha.3` which already resolved the issue, you can download it here https://github.com/Zagrios/bs-manager/releases/tag/v1.5.0-alpha.3.

Can you verify if this fixes your issue?

**Comment by Nekoraru22** [comment]
It's working perfectly now!

PD: I found a little bug with translations, I have the game in Spanish but this alert is in French:
![image](https://github.com/user-attachments/assets/f92f24a2-ed5d-4973-b001-35652612358c)

A lot of thanks!
