### ISSUE TITLE
[BUG] : Deleting playlist with "delete maps" option enabledgives an error

### ISSUE THREAD

**Issue by kek123321** [Zagrios/bs-manager#611]
### Issue encountered

tried to delete a playlist and maps together - got an error

deleting without maps works ok

![image](https://github.com/user-attachments/assets/d0e2ca48-2115-4b8c-ad05-0fb417127f4f)
![image](https://github.com/user-attachments/assets/7e01b37e-567c-47bf-a61e-ef906ef1a6ed)

### Steps to Reproduce

try to delete a playlist together with maps

### Operating System

Windows 11

### Version

1.5 alpha-4

### Additional Context

[2024-10-15-v1.5.0-alpha.4.log](https://github.com/user-attachments/files/17369429/2024-10-15-v1.5.0-alpha.4.log)

**Comment by silentrald** [comment]
@kek123321 looking at the logs, there's a broken map file that triggered the error. If you don't mind, can you check if there's any weird `info.dat` file in any of the downloaded map folders. The logs show that an `info.dat` is a binary file (I think?) and not a json file.

Also probably best if you can send the `bplist`/playlist file as well so that we can replicate your issue.

**Comment by kek123321** [comment]
ok so i dont really think looking through every single map is an option
![image](https://github.com/user-attachments/assets/db97e1f7-2012-4196-950a-27ff767010d1)
there are the playlists (none of them are deletable)
[Playlists.zip](https://github.com/user-attachments/files/17377329/Playlists.zip)
and i cant upload my ~~59 petabyte zip bomb~~ maps folder since github allows only up to 25MB
i could try to delete all maps to solve this problem but if another broken map makes its way into the game it will probably be broken again, and redownloading gigabytes of maps this often is kinda ass

**Comment by silentrald** [comment]
> i could try to delete all maps to solve this problem but if another broken map makes its way into the game it will probably be broken again, and redownloading gigabytes of maps this often is kinda ass

Hmmm, yeah that seems to be problematic. Let me see if there can be a fix to handle broken/corrupted "info.dat" files with BSM. You can hold of in nuking your songs folder in any case.

**Comment by silentrald** [comment]
@kek123321 got #613 as a workaround fix to just immediately delete map folders with corrupted `info.dat` files.

You can validate this either before or after the PR gets merged.

**Comment by silentrald** [comment]
Can you also check the latest build in any case since it added handling on those map folders. Although looking at it this doesn't delete them outright, you might have to check in the logs so see the offending map folders then delete them manually.

https://github.com/Zagrios/bs-manager/actions/runs/11352293420, click the `release-windows-latest` build.

**Comment by kek123321** [comment]
![Screenshot 2024-10-17 032522](https://github.com/user-attachments/assets/9c9d2022-09bf-4aa5-a438-c2ae2cbffae3)
after i deleted this map, i tried deleting a playlist with maps, and this time it doesnt give me any errors, however, the maps still remain in my map folder
[2024-10-17-v1.5.0-alpha.4.log](https://github.com/user-attachments/files/17404102/2024-10-17-v1.5.0-alpha.4.log)

**Comment by silentrald** [comment]
> after i deleted this map, i tried deleting a playlist with maps, and this time it doesnt give me any errors, however, the maps still remain in my map folder
2024-10-17-v1.5.0-alpha.4.log
sometimes they do get deleted, sometimes they dont

@kek123321 looked into this log file, seems that it contains a `429 too much request` error from beatsaver which just means that we're throttling the site with to many download requests, might need to add a safety net for this in BSM so that it won't do this.

<pre>
[2024-10-17 03:27:52.285] [error] Error: HTTP error! status: 429 https://beatsaver.com/api/maps/hash/beb6f5099becbe99583088f1ea924aa0118730ff
    at p.getJSON (C:\Users\meeshka\AppData\Local\Programs\bs-manager\resources\app.asar\dist\main\main.js:14:1202645)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at o.getMapsDetailsByHashs (C:\Users\meeshka\AppData\Local\Programs\bs-manager\resources\app.asar\dist\main\main.js:14:1209487)
    at C:\Users\meeshka\AppData\Local\Programs\bs-manager\resources\app.asar\dist\main\main.js:14:1210946
    at async Promise.allSettled (index 0)
    at a.getMapDetailsFromHashs (C:\Users\meeshka\AppData\Local\Programs\bs-manager\resources\app.asar\dist\main\main.js:14:1210896)
    at C:\Users\meeshka\AppData\Local\Programs\bs-manager\resources\app.asar\dist\main\main.js:14:1130198
    at C:\Users\meeshka\AppData\Local\Programs\bs-manager\resources\app.asar\dist\main\main.js:14:1130129
</pre> 

----

Did you update to this version when you tried to delete the playlists and maps?
> https://github.com/Zagrios/bs-manager/actions/runs/11352293420, click the release-windows-latest build.
