### ISSUE TITLE
[BUG] : After updating the software, I lost all my versions of Beat Saber, and re-importing them didn't work.

### ISSUE THREAD

**Issue by servalcatt** [Zagrios/bs-manager#617]
![d54984877906ace9d011d18ee12d9031](https://github.com/user-attachments/assets/d706dd4d-d76d-456c-8b95-dcb165413842)
![86247b574bf5c65193277a85c2bb299a](https://github.com/user-attachments/assets/9944cd7a-e7f0-4a05-8a54-6ec4464b990f)

**Comment by Zagrios** [comment]
Hi, can you send your logs here? (Go to Settings -> scroll down -> open Logs)
Also, check if the installation folder is set correctly. I assume it should be: `G:\BS\BSManager` for it to work. Set it to the correct folder if necessary.

**Comment by servalcatt** [comment]
[2024-10-16 14:58:59.086] [info]  Registry key "HKCU\SOFTWARE\Oculus VR, LLC\Oculus\Libraries" not found
[2024-10-16 14:58:59.091] [info]  [OUTPUT] isLivInstalled() false
[2024-10-16 14:58:59.092] [info]  Registry key "HKCU\SOFTWARE\Oculus VR, LLC\Oculus\Libraries" not found
[2024-10-16 14:58:59.093] [info]  Registry key "HKCU\SOFTWARE\Oculus VR, LLC\Oculus\Libraries" not found
[2024-10-16 14:59:00.832] [info]  Checking for update
[2024-10-16 14:59:02.954] [info]  Update for version 1.4.9 is not available (latest version: 1.4.9, downgrade is disallowed).
[2024-10-16 14:59:24.774] [error] FetchError: request to https://raw.githubusercontent.com/Zagrios/bs-manager/master/assets/jsons/bs-versions.json failed, reason: connect ETIMEDOUT 185.199.111.133:443
    at ClientRequest.<anonymous> (C:\Users\wshnr\AppData\Local\Programs\bs-manager\resources\app.asar\dist\main\main.js:14:1215369)
    at ClientRequest.emit (node:events:514:28)
    at TLSSocket.socketErrorListener (node:_http_client:501:9)
    at TLSSocket.emit (node:events:514:28)
    at emitErrorNT (node:internal/streams/destroy:151:8)
    at emitErrorCloseNT (node:internal/streams/destroy:116:3)
    at processTicksAndRejections (node:internal/process/task_queues:82:21)
[2024-10-16 14:59:24.786] [info]  getVersionOfBSFolder E:\SteamLibrary\steamapps\common\Beat Saber { steam: true }
[2024-10-16 14:59:24.798] [info]  Registry key "HKCU\SOFTWARE\Oculus VR, LLC\Oculus\Libraries" not found
[2024-10-16 14:59:24.799] [info]  Registry key "HKCU\SOFTWARE\Oculus VR, LLC\Oculus\Libraries" not found
[2024-10-16 14:59:24.801] [info]  Finded versions folders [
  'G:\\BS\\BSManager\\BSInstances\\1.37.1',
  'G:\\BS\\BSManager\\BSInstances\\Beat Saber'
]
[2024-10-16 14:59:24.802] [info]  getVersionOfBSFolder G:\BS\BSManager\BSInstances\1.37.1 undefined
[2024-10-16 14:59:24.820] [info]  unable to get version from globalgamemanagers file G:\BS\BSManager\BSInstances\1.37.1\Beat Saber_Data\globalgamemanagers
[2024-10-16 14:59:24.821] [info]  getVersionOfBSFolder G:\BS\BSManager\BSInstances\Beat Saber undefined
[2024-10-16 14:59:24.822] [info]  globalgamemanagers file not found G:\BS\BSManager\BSInstances\Beat Saber\Beat Saber_Data\globalgamemanagers
[2024-10-16 15:02:01.761] [info]  getVersionOfBSFolder E:\SteamLibrary\steamapps\common\Beat Saber { steam: true }
[2024-10-16 15:02:01.766] [info]  Registry key "HKCU\SOFTWARE\Oculus VR, LLC\Oculus\Libraries" not found
[2024-10-16 15:02:01.767] [info]  Registry key "HKCU\SOFTWARE\Oculus VR, LLC\Oculus\Libraries" not found
[2024-10-16 15:02:01.769] [info]  Finded versions folders [
  'G:\\BS\\BSManager\\BSInstances\\1.37.1',
  'G:\\BS\\BSManager\\BSInstances\\Beat Saber'
]
[2024-10-16 15:02:01.770] [info]  getVersionOfBSFolder G:\BS\BSManager\BSInstances\1.37.1 undefined
[2024-10-16 15:02:01.785] [info]  unable to get version from globalgamemanagers file G:\BS\BSManager\BSInstances\1.37.1\Beat Saber_Data\globalgamemanagers
[2024-10-16 15:02:01.786] [info]  getVersionOfBSFolder G:\BS\BSManager\BSInstances\Beat Saber undefined
[2024-10-16 15:02:01.787] [info]  globalgamemanagers file not found G:\BS\BSManager\BSInstances\Beat Saber\Beat Saber_Data\globalgamemanagers
[2024-10-16 15:02:15.492] [info]  getVersionOfBSFolder G:\BS\BSManager\BSInstances\1.37.1 undefined
[2024-10-16 15:02:15.506] [info]  unable to get version from globalgamemanagers file G:\BS\BSManager\BSInstances\1.37.1\Beat Saber_Data\globalgamemanagers
[2024-10-16 15:02:15.507] [error] Error: Unable to get BS version of path
    at C:\Users\wshnr\AppData\Local\Programs\bs-manager\resources\app.asar\dist\main\main.js:14:1023530
    at C:\Users\wshnr\AppData\Local\Programs\bs-manager\resources\app.asar\dist\main\main.js:14:768220
    at t.s._next (C:\Users\wshnr\AppData\Local\Programs\bs-manager\resources\app.asar\dist\main\main.js:14:746979)
    at t.r.next (C:\Users\wshnr\AppData\Local\Programs\bs-manager\resources\app.asar\dist\main\main.js:14:719641)
    at C:\Users\wshnr\AppData\Local\Programs\bs-manager\resources\app.asar\dist\main\main.js:14:739334
    at processTicksAndRejections (node:internal/process/task_queues:95:5) NOT_BS_FOLDER
[2024-10-16 15:02:15.515] [error] [
  [
    'Uncaught Error: Unable to get BS version of path',
    'file:///C:/Users/wshnr/AppData/Local/Programs/bs-manager/resources/app.asar/dist/renderer/renderer.js',
    2,
    646249,
    'Error: Unable to get BS version of path'
  ]
]
[2024-10-16 15:02:15.517] [info]  getVersionOfBSFolder E:\SteamLibrary\steamapps\common\Beat Saber { steam: true }
[2024-10-16 15:02:15.519] [info]  Registry key "HKCU\SOFTWARE\Oculus VR, LLC\Oculus\Libraries" not found
[2024-10-16 15:02:15.520] [info]  Registry key "HKCU\SOFTWARE\Oculus VR, LLC\Oculus\Libraries" not found
[2024-10-16 15:02:15.522] [info]  Finded versions folders [
  'G:\\BS\\BSManager\\BSInstances\\1.37.1',
  'G:\\BS\\BSManager\\BSInstances\\Beat Saber'
]
[2024-10-16 15:02:15.523] [info]  getVersionOfBSFolder G:\BS\BSManager\BSInstances\1.37.1 undefined
[2024-10-16 15:02:15.536] [info]  unable to get version from globalgamemanagers file G:\BS\BSManager\BSInstances\1.37.1\Beat Saber_Data\globalgamemanagers
[2024-10-16 15:02:15.536] [info]  getVersionOfBSFolder G:\BS\BSManager\BSInstances\Beat Saber undefined
[2024-10-16 15:02:15.538] [info]  globalgamemanagers file not found G:\BS\BSManager\BSInstances\Beat Saber\Beat Saber_Data\globalgamemanagers
[2024-10-16 15:02:31.506] [info]  getVersionOfBSFolder G:\BS\BSManager\BSInstances\1.37.1\Beat Saber_Data undefined
[2024-10-16 15:02:31.507] [info]  globalgamemanagers file not found G:\BS\BSManager\BSInstances\1.37.1\Beat Saber_Data\Beat Saber_Data\globalgamemanagers
[2024-10-16 15:02:31.508] [error] Error: Unable to get BS version of path
    at C:\Users\wshnr\AppData\Local\Programs\bs-manager\resources\app.asar\dist\main\main.js:14:1023530
    at C:\Users\wshnr\AppData\Local\Programs\bs-manager\resources\app.asar\dist\main\main.js:14:768220
    at t.s._next (C:\Users\wshnr\AppData\Local\Programs\bs-manager\resources\app.asar\dist\main\main.js:14:746979)
    at t.r.next (C:\Users\wshnr\AppData\Local\Programs\bs-manager\resources\app.asar\dist\main\main.js:14:719641)
    at C:\Users\wshnr\AppData\Local\Programs\bs-manager\resources\app.asar\dist\main\main.js:14:739334 NOT_BS_FOLDER
[2024-10-16 15:02:31.510] [info]  getVersionOfBSFolder E:\SteamLibrary\steamapps\common\Beat Saber { steam: true }
[2024-10-16 15:02:31.512] [info]  Registry key "HKCU\SOFTWARE\Oculus VR, LLC\Oculus\Libraries" not found
[2024-10-16 15:02:31.513] [info]  Registry key "HKCU\SOFTWARE\Oculus VR, LLC\Oculus\Libraries" not found
[2024-10-16 15:02:31.514] [error] [
  [
    'Uncaught Error: Unable to get BS version of path',
    'file:///C:/Users/wshnr/AppData/Local/Programs/bs-manager/resources/app.asar/dist/renderer/renderer.js',
    2,
    646249,
    'Error: Unable to get BS version of path'
  ]
]
[2024-10-16 15:02:31.516] [info]  Finded versions folders [
  'G:\\BS\\BSManager\\BSInstances\\1.37.1',
  'G:\\BS\\BSManager\\BSInstances\\Beat Saber'
]
[2024-10-16 15:02:31.516] [info]  getVersionOfBSFolder G:\BS\BSManager\BSInstances\1.37.1 undefined
[2024-10-16 15:02:31.528] [info]  unable to get version from globalgamemanagers file G:\BS\BSManager\BSInstances\1.37.1\Beat Saber_Data\globalgamemanagers
[2024-10-16 15:02:31.529] [info]  getVersionOfBSFolder G:\BS\BSManager\BSInstances\Beat Saber undefined
[2024-10-16 15:02:31.530] [info]  globalgamemanagers file not found G:\BS\BSManager\BSInstances\Beat Saber\Beat Saber_Data\globalgamemanagers
[2024-10-16 15:02:48.490] [info]  getVersionOfBSFolder G:\BS\BSManager\BSInstances\1.37.1\Beat Saber_Data undefined
[2024-10-16 15:02:48.491] [info]  globalgamemanagers file not found G:\BS\BSManager\BSInstances\1.37.1\Beat Saber_Data\Beat Saber_Data\globalgamemanagers
[2024-10-16 15:02:48.492] [error] Error: Unable to get BS version of path
    at C:\Users\wshnr\AppData\Local\Programs\bs-manager\resources\app.asar\dist\main\main.js:14:1023530
    at C:\Users\wshnr\AppData\Local\Programs\bs-manager\resources\app.asar\dist\main\main.js:14:768220
    at t.s._next (C:\Users\wshnr\AppData\Local\Programs\bs-manager\resources\app.asar\dist\main\main.js:14:746979)
    at t.r.next (C:\Users\wshnr\AppData\Local\Programs\bs-manager\resources\app.asar\dist\main\main.js:14:719641)
    at C:\Users\wshnr\AppData\Local\Programs\bs-manager\resources\app.asar\dist\main\main.js:14:739334 NOT_BS_FOLDER
[2024-10-16 15:02:48.494] [info]  getVersionOfBSFolder E:\SteamLibrary\steamapps\common\Beat Saber { steam: true }
[2024-10-16 15:02:48.497] [info]  Registry key "HKCU\SOFTWARE\Oculus VR, LLC\Oculus\Libraries" not found
[2024-10-16 15:02:48.498] [info]  Registry key "HKCU\SOFTWARE\Oculus VR, LLC\Oculus\Libraries" not found
[2024-10-16 15:02:48.499] [error] [
  [
    'Uncaught Error: Unable to get BS version of path',
    'file:///C:/Users/wshnr/AppData/Local/Programs/bs-manager/resources/app.asar/dist/renderer/renderer.js',
    2,
    646249,
    'Error: Unable to get BS version of path'
  ]
]
[2024-10-16 15:02:48.500] [info]  Finded versions folders [
  'G:\\BS\\BSManager\\BSInstances\\1.37.1',
  'G:\\BS\\BSManager\\BSInstances\\Beat Saber'
]
[2024-10-16 15:02:48.501] [info]  getVersionOfBSFolder G:\BS\BSManager\BSInstances\1.37.1 undefined
[2024-10-16 15:02:48.514] [info]  unable to get version from globalgamemanagers file G:\BS\BSManager\BSInstances\1.37.1\Beat Saber_Data\globalgamemanagers
[2024-10-16 15:02:48.514] [info]  getVersionOfBSFolder G:\BS\BSManager\BSInstances\Beat Saber undefined
[2024-10-16 15:02:48.515] [info]  globalgamemanagers file not found G:\BS\BSManager\BSInstances\Beat Saber\Beat Saber_Data\globalgamemanagers
[2024-10-16 15:03:23.959] [info]  getVersionOfBSFolder G:\BS\BSManager\BSInstances\1.37.1 undefined
[2024-10-16 15:03:23.972] [info]  unable to get version from globalgamemanagers file G:\BS\BSManager\BSInstances\1.37.1\Beat Saber_Data\globalgamemanagers
[2024-10-16 15:03:23.973] [error] Error: Unable to get BS version of path
    at C:\Users\wshnr\AppData\Local\Programs\bs-manager\resources\app.asar\dist\main\main.js:14:1023530
    at C:\Users\wshnr\AppData\Local\Programs\bs-manager\resources\app.asar\dist\main\main.js:14:768220
    at t.s._next (C:\Users\wshnr\AppData\Local\Programs\bs-manager\resources\app.asar\dist\main\main.js:14:746979)
    at t.r.next (C:\Users\wshnr\AppData\Local\Programs\bs-manager\resources\app.asar\dist\main\main.js:14:719641)
    at C:\Users\wshnr\AppData\Local\Programs\bs-manager\resources\app.asar\dist\main\main.js:14:739334
    at processTicksAndRejections (node:internal/process/task_queues:95:5) NOT_BS_FOLDER
[2024-10-16 15:03:23.975] [error] [
  [
    'Uncaught Error: Unable to get BS version of path',
    'file:///C:/Users/wshnr/AppData/Local/Programs/bs-manager/resources/app.asar/dist/renderer/renderer.js',
    2,
    646249,
    'Error: Unable to get BS version of path'
  ]
]
[2024-10-16 15:03:23.976] [info]  getVersionOfBSFolder E:\SteamLibrary\steamapps\common\Beat Saber { steam: true }
[2024-10-16 15:03:23.979] [info]  Registry key "HKCU\SOFTWARE\Oculus VR, LLC\Oculus\Libraries" not found
[2024-10-16 15:03:23.979] [info]  Registry key "HKCU\SOFTWARE\Oculus VR, LLC\Oculus\Libraries" not found
[2024-10-16 15:03:23.981] [info]  Finded versions folders [
  'G:\\BS\\BSManager\\BSInstances\\1.37.1',
  'G:\\BS\\BSManager\\BSInstances\\Beat Saber'
]
[2024-10-16 15:03:23.982] [info]  getVersionOfBSFolder G:\BS\BSManager\BSInstances\1.37.1 undefined
[2024-10-16 15:03:23.994] [info]  unable to get version from globalgamemanagers file G:\BS\BSManager\BSInstances\1.37.1\Beat Saber_Data\globalgamemanagers
[2024-10-16 15:03:23.995] [info]  getVersionOfBSFolder G:\BS\BSManager\BSInstances\Beat Saber undefined
[2024-10-16 15:03:23.996] [info]  globalgamemanagers file not found G:\BS\BSManager\BSInstances\Beat Saber\Beat Saber_Data\globalgamemanagers
[2024-10-16 15:04:11.437] [info]  getVersionOfBSFolder G:\BS\BSManager\BSInstances\Beat Saber undefined
[2024-10-16 15:04:11.438] [info]  globalgamemanagers file not found G:\BS\BSManager\BSInstances\Beat Saber\Beat Saber_Data\globalgamemanagers
[2024-10-16 15:04:11.439] [error] Error: Unable to get BS version of path
    at C:\Users\wshnr\AppData\Local\Programs\bs-manager\resources\app.asar\dist\main\main.js:14:1023530
    at C:\Users\wshnr\AppData\Local\Programs\bs-manager\resources\app.asar\dist\main\main.js:14:768220
    at t.s._next (C:\Users\wshnr\AppData\Local\Programs\bs-manager\resources\app.asar\dist\main\main.js:14:746979)
    at t.r.next (C:\Users\wshnr\AppData\Local\Programs\bs-manager\resources\app.asar\dist\main\main.js:14:719641)
    at C:\Users\wshnr\AppData\Local\Programs\bs-manager\resources\app.asar\dist\main\main.js:14:739334 NOT_BS_FOLDER
[2024-10-16 15:04:11.441] [info]  getVersionOfBSFolder E:\SteamLibrary\steamapps\common\Beat Saber { steam: true }
[2024-10-16 15:04:11.443] [info]  Registry key "HKCU\SOFTWARE\Oculus VR, LLC\Oculus\Libraries" not found
[2024-10-16 15:04:11.444] [info]  Registry key "HKCU\SOFTWARE\Oculus VR, LLC\Oculus\Libraries" not found
[2024-10-16 15:04:11.445] [error] [
  [
    'Uncaught Error: Unable to get BS version of path',
    'file:///C:/Users/wshnr/AppData/Local/Programs/bs-manager/resources/app.asar/dist/renderer/renderer.js',
    2,
    646249,
    'Error: Unable to get BS version of path'
  ]
]
[2024-10-16 15:04:11.446] [info]  Finded versions folders [
  'G:\\BS\\BSManager\\BSInstances\\1.37.1',
  'G:\\BS\\BSManager\\BSInstances\\Beat Saber'
]
[2024-10-16 15:04:11.447] [info]  getVersionOfBSFolder G:\BS\BSManager\BSInstances\1.37.1 undefined
[2024-10-16 15:04:11.459] [info]  unable to get version from globalgamemanagers file G:\BS\BSManager\BSInstances\1.37.1\Beat Saber_Data\globalgamemanagers
[2024-10-16 15:04:11.459] [info]  getVersionOfBSFolder G:\BS\BSManager\BSInstances\Beat Saber undefined
[2024-10-16 15:04:11.460] [info]  globalgamemanagers file not found G:\BS\BSManager\BSInstances\Beat Saber\Beat Saber_Data\globalgamemanagers
[2024-10-16 15:04:21.847] [info]  getVersionOfBSFolder G:\BS\BSManager\BSInstances undefined
[2024-10-16 15:04:21.848] [info]  globalgamemanagers file not found G:\BS\BSManager\BSInstances\Beat Saber_Data\globalgamemanagers
[2024-10-16 15:04:21.849] [error] Error: Unable to get BS version of path
    at C:\Users\wshnr\AppData\Local\Programs\bs-manager\resources\app.asar\dist\main\main.js:14:1023530
    at C:\Users\wshnr\AppData\Local\Programs\bs-manager\resources\app.asar\dist\main\main.js:14:768220
    at t.s._next (C:\Users\wshnr\AppData\Local\Programs\bs-manager\resources\app.asar\dist\main\main.js:14:746979)
    at t.r.next (C:\Users\wshnr\AppData\Local\Programs\bs-manager\resources\app.asar\dist\main\main.js:14:719641)
    at C:\Users\wshnr\AppData\Local\Programs\bs-manager\resources\app.asar\dist\main\main.js:14:739334 NOT_BS_FOLDER
[2024-10-16 15:04:21.851] [info]  getVersionOfBSFolder E:\SteamLibrary\steamapps\common\Beat Saber { steam: true }
[2024-10-16 15:04:21.853] [info]  Registry key "HKCU\SOFTWARE\Oculus VR, LLC\Oculus\Libraries" not found
[2024-10-16 15:04:21.854] [info]  Registry key "HKCU\SOFTWARE\Oculus VR, LLC\Oculus\Libraries" not found
[2024-10-16 15:04:21.855] [error] [
  [
    'Uncaught Error: Unable to get BS version of path',
    'file:///C:/Users/wshnr/AppData/Local/Programs/bs-manager/resources/app.asar/dist/renderer/renderer.js',
    2,
    646249,
    'Error: Unable to get BS version of path'
  ]
]
[2024-10-16 15:04:21.856] [info]  Finded versions folders [
  'G:\\BS\\BSManager\\BSInstances\\1.37.1',
  'G:\\BS\\BSManager\\BSInstances\\Beat Saber'
]
[2024-10-16 15:04:21.857] [info]  getVersionOfBSFolder G:\BS\BSManager\BSInstances\1.37.1 undefined
[2024-10-16 15:04:21.868] [info]  unable to get version from globalgamemanagers file G:\BS\BSManager\BSInstances\1.37.1\Beat Saber_Data\globalgamemanagers
[2024-10-16 15:04:21.869] [info]  getVersionOfBSFolder G:\BS\BSManager\BSInstances\Beat Saber undefined
[2024-10-16 15:04:21.870] [info]  globalgamemanagers file not found G:\BS\BSManager\BSInstances\Beat Saber\Beat Saber_Data\globalgamemanagers


> 您好，您能将您的日志发送到这里吗？（转到设置 - >向下滚动 - >打开日志）此外，请检查安装文件夹是否设置正确。我认为对你来说应该是：让它起作用。如有必要，请将其设置为正确的文件夹。`G:\BS\BSManager`

**Comment by Zagrios** [comment]
Oh ok, don't change anything.
The error comes from the fact that you are unable to get the latest versions of Beat Saber due to a timeout error.

Try restarting or switching your Internet connection, and disable your VPN if you have one.

If nothing works, try installing the latest alpha from here: https://github.com/Zagrios/bs-manager/releases/tag/v1.5.0-alpha.4

**Comment by servalcatt** [comment]
> 哦，好吧，不要改变任何东西。该错误来自于由于超时错误而无法获取最新版本的 Beat Saber。
> 
> 尝试重新启动您的 PC，重新启动或切换您的 Internet 连接，并禁用您的 VPN（如果有）。
> 
> 如果没有任何效果，请尝试从以下位置安装最新的 Alpha 版本：https://github.com/Zagrios/bs-manager/releases/tag/v1.5.0-alpha.4

After the method you described didn't work, I tried the Alpha version. It's working now, thank you!

**Comment by Zagrios** [comment]
🎉 🎉
