### ISSUE TITLE
[BUG] : My mod loader remains stuck on Loading Mods

### ISSUE THREAD

**Issue by ArsTrickster** [Zagrios/bs-manager#705]
![image](https://github.com/user-attachments/assets/d15ef7c8-a87c-4a64-977d-4b167e096263)

I honestly don't know what to do, i tryed switching to an old version of bsmanager, an alpha one, downloading other versions, launching as admin, idk, it just won't load

**Comment by silentrald** [comment]
@ArsTrickster
Can you please send your logs here?
(Go to settings -> Scroll down -> "Open Logs")

**Comment by ArsTrickster** [comment]
[2024-12-16-v1.4.14.log](https://github.com/user-attachments/files/18179902/2024-12-16-v1.4.14.log)
[2024-12-17-v1.4.14.log](https://github.com/user-attachments/files/18179903/2024-12-17-v1.4.14.log)
[2024-12-18-v1.4.13.log](https://github.com/user-attachments/files/18179904/2024-12-18-v1.4.13.log)
[2024-12-18-v1.4.14.log](https://github.com/user-attachments/files/18179905/2024-12-18-v1.4.14.log)
[2024-12-18-v1.5.0-alpha.6.log](https://github.com/user-attachments/files/18179906/2024-12-18-v1.5.0-alpha.6.log)



Here they are! Thank you in advance <3

**Comment by silentrald** [comment]
@ArsTrickster
Can you try accessing this file in your browser: https://alias.beatmods.com/aliases.json. Seems that BSManager can't reach these sites and making the mods list to not load.

**Comment by ArsTrickster** [comment]
the websites seems to open good
![image](https://github.com/user-attachments/assets/4e237ac2-b61e-48ac-986f-a74d19296206)
![image](https://github.com/user-attachments/assets/73c29c60-e3dd-4945-8642-3f92576451db)

**Comment by silentrald** [comment]
@ArsTrickster
Do you have a proxy setup with your PC, or anything that might change your network like a VPN or some sort?

**Comment by ArsTrickster** [comment]
I don't have a proxy - vpn tbh, but def the dns is tripping, im also having some troubles with discord lately so that might be it, im gonna check out

**Comment by ArsTrickster** [comment]
Nothing, both dns servers don't work
and to add more, one random time after i tryed changing the default browser, the mod loader worked, then i closed it up and it looped again

**Comment by silentrald** [comment]
@ArsTrickster
Does this only affect your mods tab? Can you check if you can download songs/maps/playlists as well if the same issue persists there. Either there's something wrong with the network accessing the website or there is something wrong with the code.

**Comment by ArsTrickster** [comment]
Sorry i was a bit busy, by the way, i tryed, i can't download songs. but i can download models for some reason
Probably a problem of mine with the network i guess?

**Comment by silentrald** [comment]
@ArsTrickster
Would probably check if the IP address that BSM is using is the same with ping to be honest. I'm not quite certain if that is even possible though but you could check.

Try to access the mod list, then check for the IP address that failed, something like this `connect ETIMEDOUT 188.114.96.7:443`. Then try to ping beatmods site using command prompt and see if the two matches.

Can you also check if you can access the site thru IPv6. BSManager couldn't get the IPv6 for `alias.beatmods.com` so maybe that can be the issue as well.

**Comment by nalloyd2** [comment]
Experiencing the same all of a sudden today. Was working fine not 30 minutes ago then stopped working after exited the game to try and download a mod. May be worth noting that I was trying to access BSM while BS was still open. Here's what looks to be the problem from logs:

> [2025-01-01 18:06:57.513] [error] Error: HTTP error! status: 400 https://beatmods.com/api/v1/mod
    at m.getJSON (C:\Users\REDACTED\AppData\Local\Programs\bs-manager\resources\app.asar\dist\main\main.js:14:1045681)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at w.getInstalledMods (C:\Users\REDACTED\AppData\Local\Programs\bs-manager\resources\app.asar\dist\main\main.js:14:1040523) undefined

**Comment by RileyEndymion** [comment]
Me and one other person were just about to mod ours and play, and same with both of ours, mods tab won't load. Logs say same thing.

**Comment by halytech** [comment]
I'm hanging as well. The API response on the 400 error returns:

{"message":"No valid game version."}

This seems to be returned regardless of the game version.

**Comment by Zagrios** [comment]
@nalloyd2 @RileyEndymion The API that we use to get mods has got an update, A patch is coming soon to fix that

**Comment by nalloyd2** [comment]
> @nalloyd2 @RileyEndymion The API that we use to get mods has got an update, A patch is coming soon to fix that

Got it just bad timing then. Thanks for the quick follow up! Much appreciated.

**Comment by Zagrios** [comment]
@RileyEndymion @halytech @nalloyd2 should be fixed in the latest release 👌

**Comment by zzxbzebze** [comment]
@silentrald Hi, I have the same problem with mods. The two websites you mentioned here won't open for me. Can you please help?
